googleinterns/techish

cloudbuild.yaml

This change adds a cloud build configuration for this repo which can enable automatically deploying an app after a new commit.

Add cloudbuild.yaml file

---

cloudbuild.yaml

This change updates the cloud build file to build the maven package.

Update Cloud Build file to build the maven package.

---

src/main/webapp/index.html

The body onload somehow got deleted when merging PRs, just adding it back

small change for load comments

---

src/main/java/com/google/sps/servlets/MatchServlet.java
src/main/webapp/index.html
src/main/webapp/logged_in_homepage.html
src/test/java/com/google/sps/MatchServletTest.java

Popup window to display new matches

---

src/main/webapp/ts/login.js

PTAL
I recompiled login.ts bc the Login/Logout didn't work. Now it should work.

Recompiled login.ts file

---

src/main/java/com/google/sps/algorithms/MatchQuery.java
src/main/java/com/google/sps/data/NonPersistentUserRepository.java
src/main/java/com/google/sps/data/User.java
src/main/java/com/google/sps/data/UserRepository.java
src/test/java/com/google/sps/MatchServletTest.java
src/test/java/com/google/sps/NonPersistentUserRepositoryTest.java
src/test/java/com/google/sps/UserTest.java

Created database structure for all-user database including a NonPersistentUserRepository that stores fake users in an ArrayList.

Set up hard-coded mentors to be used in MVP matching algorithm

---

package-lock.json
package.json
src/main/webapp/logged_in_homepage.html
src/main/webapp/ts/matches.js
src/main/webapp/ts/matches.ts

Added a different popup for when no matches are found:

No New Matches Popup

---

src/main/java/com/google/sps/algorithms/MatchQuery.java
src/main/java/com/google/sps/data/MatchRequest.java
src/main/java/com/google/sps/data/NonPersistentMatchRepository.java
src/main/java/com/google/sps/data/NonPersistentUserRepository.java
src/main/java/com/google/sps/data/User.java
src/main/java/com/google/sps/data/UserRepository.java
src/main/java/com/google/sps/servlets/MatchServlet.java
src/main/java/com/google/sps/servlets/NewMatchQueryServlet.java
src/main/webapp/logged_in_homepage.html
src/main/webapp/ts/matches.js
src/main/webapp/ts/matches.ts
src/test/java/com/google/sps/MatchQueryTest.java
src/test/java/com/google/sps/MatchRequestTest.java
src/test/java/com/google/sps/MatchServletTest.java
src/test/java/com/google/sps/NewMatchQueryServletTest.java
src/test/java/com/google/sps/NonPersistentMatchRepositoryTest.java
src/test/java/com/google/sps/NonPersistentUserRepositoryTest.java
src/test/java/com/google/sps/UserTest.java

Changes made:
- renamed `productArea` variable `specialties` because it made more sense to me
- added drop-down menu with choices for specialties to match by
- updated algorithm to return matches with selected specialty
- added stringToUser method to convert javascript string back to User in Java

Matching Algorithm Progress

---

src/main/java/com/google/sps/algorithms/MatchQuery.java
src/main/java/com/google/sps/data/User.java
src/main/java/com/google/sps/servlets/MatchServlet.java
src/main/java/com/google/sps/servlets/NewMatchQueryServlet.java
src/main/webapp/logged_in_homepage.html
src/test/java/com/google/sps/MatchQueryTest.java
src/test/java/com/google/sps/MatchServletTest.java
src/test/java/com/google/sps/NewMatchQueryServletTest.java

I added ServletContext functionality to both MatchServlet.java and NewMatchQueryServlet.java so that they can share variables. This is so that the MatchQuery file can access the user's saved matches which are stored in the MatchServlet.

Algorithm doesn't return matches that are already saved

---

src/main/webapp/css/profileBuilder.css

Changed button text to a dark gray color

---

src/main/java/com/google/sps/data/NonPersistentUserRepository.java
src/main/webapp/ts/matches.js
src/main/webapp/ts/matches.ts

Changes:
- added fake emails to NonPersistentUserRepository entries
- made a matchToString function to display the matches in a better way

Display email for matches

---

src/main/webapp/index.html

Wrote up some quick paragraphs to fill in the homepage, feel free to edit/change!!

Update Paragraphs on Logged Out Page

---

src/main/java/com/google/sps/servlets/ProfileBuilderServlet.java
src/main/webapp/profileBuilder.html
src/main/webapp/ts/profileBuilder.js
src/main/webapp/ts/profileBuilder.ts

PTAL The form works now to submit.

made minor changes form for profileBuilder

---

src/main/webapp/index.html
src/main/webapp/ts/login.js
src/main/webapp/ts/login.ts

Implement style feature to hide sign up link only when the user is loggedIn. 
[Feature Image](https://screenshot.googleplex.com/OvMTvGkhmER.png)
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

LoggedOut Homepage Feature

---

src/main/webapp/index.html
src/main/webapp/ts/login.js
src/main/webapp/ts/login.ts

Removed the SignUp Link from the index.html

Removed SignUp Link from LoggedOutPage

---

src/main/webapp/css/landing.css

Changed a style attribute for the images on the landing page. They know are round and stay circular. This change was made so that mobile users could have a better view.
_Put an x in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

User Interface Responsive Design Feature

---

src/main/webapp/ts/login.ts
src/main/webapp/ts/profileBuilder.js
src/main/webapp/ts/profileBuilder.ts

Created redirect condition for users who aren't logged in users that try to go to the profileBuilder page by url.

Redirect for Users who visit ProfileBuilder but aren't logged in.

---

src/main/java/com/google/sps/algorithms/MatchQuery.java
src/main/java/com/google/sps/data/PersistentMatchRepository.java
src/main/java/com/google/sps/data/PersistentUserRepository.java
src/main/java/com/google/sps/data/User.java
src/main/java/com/google/sps/servlets/ProfileBuilderServlet.java
src/main/webapp/css/landing.css
src/main/webapp/logged_in_homepage.html
src/main/webapp/profileBuilder.html
src/main/webapp/ts/matches.js
src/main/webapp/ts/matches.ts
src/test/java/com/google/sps/PersistentUserRepositoryTest.java

Updated the UI for saved matches and added a user bio section which will be used for the match ranking in the future.

Update Saved Matches UI & Add User Bio

---

src/main/webapp/profileBuilder.html
src/main/webapp/ts/profileBuilder.ts

Modified profileBuilder so that it hides the form when a user visits the page. Once they select a specific profileType form then they will fill out the form and not get a server error.

ProfileBuilder Server Error

---

src/main/webapp/index.html
src/main/webapp/ts/matches.js
src/main/webapp/ts/matches.ts

Implemented BugFix for GetMatches Logged-Out users. The fix: When logged-out user hits get matches button, they go to the page. Get this alert: This feature works for signed-in users. Click here to learn more. User clicks the button. Redirects to index page but goes to the learn more div which is where the description of the platform exists. 

Get Matches Logged-Out User Bug

---

src/main/java/com/google/sps/algorithms/AbuseDetection.java
src/test/java/com/google/sps/AbuseDetectionTest.java

Created Rate Limiting Abuse Detection Feature that takes the local time of a requests based on the time range and amount allowed, and determines whether the request fits both or does not. Also added tests for this.

Rate Limiting Abuse Detection Feature

---

src/main/webapp/css/profileBuilder.css
src/main/webapp/profileBuilder.html

Added center alignment css feature, and wrote down some descriptions about both forms.
[Mentee Form Image](https://screenshot.googleplex.com/QXWC11X6ETU.png)
[Mentor Form Image](https://screenshot.googleplex.com/fDMV9kbYEqX)

ProfileBuilder Centering and Descriptions 

---

src/main/webapp/profileBuilder.html
src/main/webapp/ts/profileBuilder.js
src/main/webapp/ts/profileBuilder.ts

Implemented BugFix for ProfileBuilder. It makes the inputs become required only based on the form selected. Example: if user selects mentee, those inputs are required in order to submit. 

Implemented require statements in Javascript

---

src/main/webapp/css/profileBuilder.css
src/main/webapp/profileBuilder.html

Added spacing, made the mentee/mentor button text black.

ProfileBuilder Styling

---

src/main/webapp/ts/matches.js
src/main/webapp/ts/matches.ts

I'm pretty sure this fixed the bug, I just added a check to make sure the email wasn't null before printing it

Fixed email=null bug
